# Generated by Django 4.2.4 on 2023-09-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_craft_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default=None, upload_to='products/'),
        ),
    ]
