# Generated by Django 4.2.4 on 2023-09-01 14:56

import django.core.validators
from django.db import migrations, models
import user.validations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[user.validations.validate_length, django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
